#pragma once

#define TAXI_CAM_VERSION "0.8.0"
#define TAXI_CAM_VERSION_MAJOR 0
#define TAXI_CAM_VERSION_MINOR 8
#define TAXI_CAM_VERSION_PATCH 0

#ifndef TAXI_CAM_BUILD_NUMBER
#define TAXI_CAM_BUILD_NUMBER 0
#endif

#define TAXI_CAM_STRINGIFY_IMPL(value) #value
#define TAXI_CAM_STRINGIFY(value) TAXI_CAM_STRINGIFY_IMPL(value)
#define TAXI_CAM_RELEASE_VERSION TAXI_CAM_VERSION "-build." TAXI_CAM_STRINGIFY(TAXI_CAM_BUILD_NUMBER)
