#pragma once

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <d3d12.h>
#include <d3d12sdklayers.h>
#include <d3dcompiler.h>
#include <dxgi1_4.h>
#include <windows.h>

#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <limits>
#include <stdexcept>
#include <string>
#include <vector>

#include "gpu_queue.hpp"
#include "../../src/graphics/camera_compositor_d3d12.hpp"
#include "../../src/graphics/display_exposure.hpp"
#include "reference_overlay_oracle.hpp"

namespace taxi_camera::testing {
using Compositor = taxi_camera::CameraCompositorD3D12;

template <typename T>
class Reference {
 public:
  Reference() = default;
  Reference(const Reference&) = delete;
  Reference& operator=(const Reference&) = delete;
  ~Reference() {
    if (value_)
      value_->Release();
  }
  T* get() const { return value_; }
  T* operator->() const { return value_; }
  T** put() { return &value_; }

 private:
  T* value_ = nullptr;
};

inline void require(bool condition, const char* message) {
  if (!condition)
    throw std::runtime_error(message);
}

inline void check(HRESULT status, const char* message) {
  if (FAILED(status)) {
    char error[1400]{};
    std::snprintf(error, sizeof(error), "%s (HRESULT 0x%08lx)", message, static_cast<unsigned long>(status));
    throw std::runtime_error(error);
  }
}

inline D3D12_HEAP_PROPERTIES heap_properties(D3D12_HEAP_TYPE type) {
  D3D12_HEAP_PROPERTIES heap{};
  heap.Type = type;
  heap.CreationNodeMask = heap.VisibleNodeMask = 1;
  return heap;
}

inline D3D12_RESOURCE_DESC texture_description(UINT width, UINT height, DXGI_FORMAT format) {
  D3D12_RESOURCE_DESC description{};
  description.Dimension = D3D12_RESOURCE_DIMENSION_TEXTURE2D;
  description.Width = width;
  description.Height = height;
  description.DepthOrArraySize = description.MipLevels = 1;
  description.Format = format;
  description.SampleDesc.Count = 1;
  description.Flags = D3D12_RESOURCE_FLAG_ALLOW_RENDER_TARGET;
  return description;
}

inline void create_texture(ID3D12Device* device, const D3D12_RESOURCE_DESC& description, ID3D12Resource** output) {
  const auto heap = heap_properties(D3D12_HEAP_TYPE_DEFAULT);
  check(device->CreateCommittedResource(&heap, D3D12_HEAP_FLAG_NONE, &description, D3D12_RESOURCE_STATE_RENDER_TARGET, nullptr,
                                        IID_PPV_ARGS(output)),
        "Create validation texture");
}

inline void transition(ID3D12GraphicsCommandList* list, ID3D12Resource* resource, D3D12_RESOURCE_STATES before, D3D12_RESOURCE_STATES after) {
  if (before == after)
    return;
  D3D12_RESOURCE_BARRIER barrier{};
  barrier.Type = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
  barrier.Transition = {resource, 0, before, after};
  list->ResourceBarrier(1, &barrier);
}

class PrivateSubmission {
 public:
  explicit PrivateSubmission(ID3D12Device* device) : device_(device) {
    D3D12_COMMAND_QUEUE_DESC queue{};
    queue.Type = D3D12_COMMAND_LIST_TYPE_DIRECT;
    check(device->CreateCommandQueue(&queue, IID_PPV_ARGS(queue_.put())), "Create private queue");
    check(device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT, IID_PPV_ARGS(allocator_.put())), "Create private allocator");
    check(device->CreateCommandList(0, D3D12_COMMAND_LIST_TYPE_DIRECT, allocator_.get(), nullptr, IID_PPV_ARGS(list_.put())),
          "Create private command list");
  }

  ID3D12GraphicsCommandList* list() const { return list_.get(); }

  void finish(Compositor& compositor) {
    check(list_->Close(), "Close private list");
    ID3D12CommandList* lists[]{list_.get()};
    queue_->ExecuteCommandLists(1, lists);
    if (!taxi_camera::drain_copy_queue(queue_.get(), device_)) {
      compositor.abandon();
      // Do not destroy any submitted test resources after an unverified drain.
      // Exit the isolated host immediately; no simulator process is involved.
      std::fputs("FAIL: private GPU queue completion could not be established.\n", stderr);
      ExitProcess(1);
    }
    check(device_->GetDeviceRemovedReason(), "Device health after composition");
  }

 private:
  Reference<ID3D12CommandQueue> queue_;
  Reference<ID3D12CommandAllocator> allocator_;
  Reference<ID3D12GraphicsCommandList> list_;
  ID3D12Device* device_;
};

// Test-only source producer. Every input pixel is generated by a GPU shader;
// no CPU camera-frame upload, texture readback or simulator input is involved.
class GradientGenerator {
 public:
  explicit GradientGenerator(ID3D12Device* device) {
    constexpr char Shader[] = R"(
cbuffer Parameters : register(b0) { uint Width; uint Height; uint Frame; uint Source; };
float4 vs_main(uint id : SV_VertexID) : SV_Position {
  float2 uv = float2((id << 1) & 2, id & 2);
  return float4(uv.x * 2 - 1, 1 - uv.y * 2, 0, 1);
}
float4 ps_main(float4 position : SV_Position) : SV_Target {
  float2 xy = (position.xy - 0.5) / float2(max(Width - 1, 1), max(Height - 1, 1));
  float red = Frame == 0 ? xy.x : 1 - xy.x;
  float green = Source == 0 ? xy.y : 1 - xy.y;
  float blue = Frame == 0 ? (Source == 0 ? 0.2 : 0.8) : (Source == 0 ? 0.6 : 0.4);
  return float4(red, green, blue, 0.25);
}
)";
    D3D12_ROOT_PARAMETER parameter{};
    parameter.ParameterType = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
    parameter.Constants.Num32BitValues = 4;
    parameter.ShaderVisibility = D3D12_SHADER_VISIBILITY_PIXEL;
    D3D12_ROOT_SIGNATURE_DESC signature{};
    signature.NumParameters = 1;
    signature.pParameters = &parameter;
    Reference<ID3DBlob> serialized;
    check(D3D12SerializeRootSignature(&signature, D3D_ROOT_SIGNATURE_VERSION_1, serialized.put(), nullptr),
          "Serialize generator signature");
    check(device->CreateRootSignature(0, serialized->GetBufferPointer(), serialized->GetBufferSize(), IID_PPV_ARGS(root_.put())),
          "Create generator signature");
    Reference<ID3DBlob> vertex;
    Reference<ID3DBlob> pixel;
    check(D3DCompile(Shader, sizeof(Shader) - 1, "validation_gradient", nullptr, nullptr, "vs_main", "vs_5_0",
                     D3DCOMPILE_ENABLE_STRICTNESS | D3DCOMPILE_OPTIMIZATION_LEVEL3, 0, vertex.put(), nullptr),
          "Compile generator vertex shader");
    check(D3DCompile(Shader, sizeof(Shader) - 1, "validation_gradient", nullptr, nullptr, "ps_main", "ps_5_0",
                     D3DCOMPILE_ENABLE_STRICTNESS | D3DCOMPILE_OPTIMIZATION_LEVEL3, 0, pixel.put(), nullptr),
          "Compile generator pixel shader");
    D3D12_GRAPHICS_PIPELINE_STATE_DESC pipeline{};
    pipeline.pRootSignature = root_.get();
    pipeline.VS = {vertex->GetBufferPointer(), vertex->GetBufferSize()};
    pipeline.PS = {pixel->GetBufferPointer(), pixel->GetBufferSize()};
    auto& blend = pipeline.BlendState.RenderTarget[0];
    blend.SrcBlend = blend.SrcBlendAlpha = D3D12_BLEND_ONE;
    blend.DestBlend = blend.DestBlendAlpha = D3D12_BLEND_ZERO;
    blend.BlendOp = blend.BlendOpAlpha = D3D12_BLEND_OP_ADD;
    blend.LogicOp = D3D12_LOGIC_OP_NOOP;
    blend.RenderTargetWriteMask = D3D12_COLOR_WRITE_ENABLE_ALL;
    pipeline.SampleMask = UINT_MAX;
    pipeline.RasterizerState.FillMode = D3D12_FILL_MODE_SOLID;
    pipeline.RasterizerState.CullMode = D3D12_CULL_MODE_NONE;
    pipeline.RasterizerState.DepthClipEnable = TRUE;
    pipeline.DepthStencilState.DepthFunc = D3D12_COMPARISON_FUNC_ALWAYS;
    pipeline.DepthStencilState.FrontFace = {D3D12_STENCIL_OP_KEEP, D3D12_STENCIL_OP_KEEP, D3D12_STENCIL_OP_KEEP,
                                            D3D12_COMPARISON_FUNC_ALWAYS};
    pipeline.DepthStencilState.BackFace = pipeline.DepthStencilState.FrontFace;
    pipeline.PrimitiveTopologyType = D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE;
    pipeline.NumRenderTargets = 1;
    pipeline.SampleDesc.Count = 1;
    pipeline.RTVFormats[0] = DXGI_FORMAT_R8G8B8A8_UNORM;
    check(device->CreateGraphicsPipelineState(&pipeline, IID_PPV_ARGS(rgba_.put())), "Create RGBA gradient pipeline");
    pipeline.RTVFormats[0] = DXGI_FORMAT_B8G8R8A8_UNORM;
    check(device->CreateGraphicsPipelineState(&pipeline, IID_PPV_ARGS(bgra_.put())), "Create BGRA gradient pipeline");
  }

  void
  record(ID3D12GraphicsCommandList* list, D3D12_CPU_DESCRIPTOR_HANDLE rtv, UINT width, UINT height, bool bgra, UINT frame, UINT source) {
    list->SetGraphicsRootSignature(root_.get());
    list->SetPipelineState(bgra ? bgra_.get() : rgba_.get());
    const std::array<UINT, 4> parameters{width, height, frame, source};
    list->SetGraphicsRoot32BitConstants(0, static_cast<UINT>(parameters.size()), parameters.data(), 0);
    list->IASetPrimitiveTopology(D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
    const D3D12_VIEWPORT viewport{0, 0, static_cast<float>(width), static_cast<float>(height), 0, 1};
    const D3D12_RECT scissor{0, 0, static_cast<LONG>(width), static_cast<LONG>(height)};
    list->RSSetViewports(1, &viewport);
    list->RSSetScissorRects(1, &scissor);
    list->OMSetRenderTargets(1, &rtv, FALSE, nullptr);
    list->DrawInstanced(3, 1, 0, 0);
  }

 private:
  Reference<ID3D12RootSignature> root_;
  Reference<ID3D12PipelineState> rgba_;
  Reference<ID3D12PipelineState> bgra_;
};

}  // namespace taxi_camera::testing
